#!/bin/bash
# example of how to use this docker image to build for serranoveltexx

# build the docker image if not already done
if test ! -f docker-id; then
  cd docker
  docker build --iidfile=../docker-id .
  cd ..
fi

# build for serranoveltexx with su and microG included, sign the build
# (keys are autogenerated if they don't already exist in the keys dir)
docker run \
-e "RELEASE_TYPE=microG-su-UNOFFICIAL" \
-e "DEVICE_LIST=serranoveltexx" \
-e "BRANCH_NAME=cm-14.1" \
-e "WITH_SU=true" \
-e "INCLUDE_PROPRIETARY=false" \
-e "SIGNATURE_SPOOFING=restricted" \
-e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore FDroid FDroidPrivilegedExtension MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar" \
-e "CRONTAB_TIME=now" \
-e "SIGN_BUILDS=true" \
-v "$HOME/.ccache:/srv/ccache" \
-v "$HOME/android/lineageos:/srv/src" \
-v "$(pwd)/zips:/srv/zips" \
-v "$(pwd)/local_manifests:/srv/local_manifests" \
-v "$(pwd)/keys:/srv/keys" \
-v "$(pwd)/logs:/srv/logs" \
$(cat docker-id)
